# Numpy Exercise

#### 1. Import the numpy package under the name  (★☆☆)

import numpy as np

#### 2. Print the numpy version and the configuration  (★☆☆)

In [8]:
print (np.__version__)
print (np.show_config())

1.17.2
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/soumyadeeppaul/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/soumyadeeppaul/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/soumyadeeppaul/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/soumyadeeppaul/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/soumyadeeppaul/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/soumyadeeppaul/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/soumyadeeppaul/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/soumyadeeppaul/opt/anaconda3/inc

#### 3. Create a null vector of size 10 (★☆☆)

In [9]:
arr = np.zeros(10)
print (arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [11]:
print (arr.size * arr.itemsize)

80


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [12]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None`

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [13]:
arr = np.zeros(10)
arr[4] = 1
print (arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [15]:
arr = np.arange(10, 50, 1)
print (arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [17]:
arr = arr[::-1]
print (arr)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [18]:
arr = np.arange(0, 9, 1).reshape(3, 3)
print (arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [19]:
ind = np.nonzero([1,2,0,0,4,0])
print(ind)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [21]:
arr = np.ones((3, 3))
print (arr)

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [23]:
arr = np.random.random((3, 3))
print (arr)

[[0.11084659 0.00144711 0.38756029]
 [0.76849866 0.58109852 0.25128757]
 [0.61870671 0.1937111  0.95251094]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [25]:
arr = np.random.random((10, 10))
print (arr.min(), arr.max())

0.026920370638992774 0.9887487317515344


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [26]:
arr = np.random.random(30)
print (arr.mean())

0.42672190525802584


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [28]:
arr = np.ones((10, 10))
arr[1:-1, 1:-1] = 0
print (arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [30]:
arr = np.random.random((10, 10))
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print (arr)

[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.12477003 0.18427107 0.51351172 0.61276724 0.52663532
  0.61282816 0.74874616 0.74846103 0.66055596 0.1593741  0.        ]
 [0.         0.05619905 0.40659835 0.4468947  0.53673357 0.04671656
  0.49570175 0.89278008 0.68173513 0.67798363 0.99220816 0.        ]
 [0.         0.81678564 0.05115067 0.31263699 0.31904129 0.14315311
  0.00931893 0.71573626 0.89925742 0.28478468 0.2286988  0.        ]
 [0.         0.18089618 0.35213852 0.69062291 0.65162524 0.90657832
  0.34568075 0.76110187 0.18373236 0.21364251 0.17500262 0.        ]
 [0.         0.54965917 0.72632365 0.4118807  0.8075161  0.89544206
  0.34219654 0.54698209 0.9501669  0.57687056 0.94049543 0.        ]
 [0.         0.02597761 0.86932567 0.90105842 0.03914642 0.51620086
  0.17505112 0.50298268 0.18583145 0.90044632 0.08557045 0.        ]
 [0.         0.25815133 0.08275093 0.96397734 0.3

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [35]:
print (0 * np.nan)
print (np.nan == np.nan)
print (np.inf > np.nan)
print (np.nan - np.nan)
print (np.nan in set([np.nan]))
print (0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [38]:
arr = np.diag(np.arange(1,a 5, 1),k=-1)
print (arr)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [47]:
arr = np.zeros((8,8))
arr.dtype = 'int'
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
print(np.unravel_index(99,(6,7,8)))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [48]:
arr = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [50]:
arr = np.random.random((5, 5))
arr = (arr - np.mean(arr))/np.std(arr)
print (arr)

[[-0.06209312  1.41944467  0.81094879 -0.98049424  1.37279122]
 [-0.24252071 -0.48320333  1.34079465 -0.84431675 -1.34705626]
 [ 0.26046325 -1.37180436 -1.36540485  0.12216576 -0.39705845]
 [-0.32987825  0.55479297 -0.87511408  1.65015725 -0.24507346]
 [-0.29450579  1.52746736 -1.31289148 -0.4949456   1.5873348 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [55]:
color = np.dtype([('r', np.ubyte, (1, )), ('grades', np.ubyte, (1, ))])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [56]:
arr1 = np.random.random((5, 3))
arr2 = np.random.random((3, 2))
arr = arr1.dot(arr2)
print (arr)

[[1.06944889 0.76584574]
 [0.98624249 0.66059057]
 [1.57590073 1.17906808]
 [0.73539675 0.66016921]
 [1.25388    0.98742175]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [62]:
arr = np.arange(1, 20, 1)
arr[(arr>=3) & (arr<=8)] *= -1
print (arr)

[ 1  2 -3 -4 -5 -6 -7 -8  9 10 11 12 13 14 15 16 17 18 19]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [63]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
All the expressions are legal except the last one.

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [73]:
print (np.array(0) / np.array(0))
print (np.array(0) // np.array(0))
print (np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/Users/soumyadeeppaul/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/Users/soumyadeeppaul/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆)

In [77]:
arr = np.random.uniform(-10,+10,10)
print (arr)
arr = np.ceil(arr)
print (arr)

[ 0.76363294 -3.44204541 -8.29273306 -2.61802487  2.61912676  0.51325749
 -9.18460949  6.65043402 -0.77311288  3.65496529]
[ 1. -3. -8. -2.  3.  1. -9.  7. -0.  4.]


#### 30. How to find common values between two arrays? (★☆☆)

In [78]:
arr1 = np.random.randint(-10,10,10)
print (arr1)
arr2 = np.random.randint(-10,10,10)
print (arr2)
print(np.intersect1d(arr1,arr2))

[-4 -8 -9  3  7  9 -9 -7  5  2]
[  9   4   6   6   4  -9  -9 -10   9   4]
[-9  9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
defaults = np.seterr(all="ignore")

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [79]:
print (np.sqrt(-1) == np.emath.sqrt(-1))

False


/Users/soumyadeeppaul/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [80]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print (yesterday)
print (today)
print (tomorrow)

2019-12-25
2019-12-26
2019-12-27


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
arr = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(arr)

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [91]:
a = np.random.randint(-10, 10, 10)
b = np.random.randint(-10, 10, 10)
c = np.random.randint(-10, 10, 10)
print ((a+b)*(-a/2))

[ -0.  -22.5 -12.    3.5 -13.5 -18.    1.5 -45.   -4.    0. ]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [85]:
arr = np.random.uniform(0,10,10)
print (arr - arr%1)
print (np.floor(arr))
print (np.ceil(arr)-1)
print (arr.astype(int))
print (np.trunc(arr))

[2. 5. 3. 1. 8. 8. 7. 6. 8. 5.]
[2. 5. 3. 1. 8. 8. 7. 6. 8. 5.]
[2. 5. 3. 1. 8. 8. 7. 6. 8. 5.]
[2 5 3 1 8 8 7 6 8 5]
[2. 5. 3. 1. 8. 8. 7. 6. 8. 5.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [86]:
arr = np.zeros((5, 5))
arr = arr + np.arange(0, 5, 1)
print (arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [92]:
arr = np.random.randint(0, 100, 10)
print (arr)

[72 66 20 21 75 35 62 86 86 50]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [96]:
arr = np.random.random((1, 10))
print (arr)

[[0.41645749 0.89412499 0.34854707 0.53192849 0.06226852 0.48036212
  0.5143461  0.89219473 0.83724926 0.64822445]]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [98]:
arr = np.random.random((1, 10))
arr.sort()
print (arr)

[[0.01625287 0.20446244 0.21328059 0.24376356 0.45450161 0.46872749
  0.47718486 0.49035697 0.5751879  0.62495477]]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [99]:
arr = np.arange(10)
np.add.reduce(arr)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [100]:
arr1 = np.random.randint(-10, 10, 10)
arr2 = np.random.randint(-10, 10, 10)
print (np.array_equal(arr1, arr2))

False


#### 43. Make an array immutable (read-only) (★★☆)

In [101]:
x = np.zeros(10)
x.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [103]:
arr = np.random.random((10,2))
x,y = arr[:,0], arr[:,1]
r = np.sqrt(x**2 + y**2)
t = np.arctan2(y, x)
print (r)
print (t)

[0.64976836 0.94987616 0.78398072 1.1405037  0.15744863 0.44525311
 1.14536783 0.74531428 0.29160317 0.43870532]
[0.79752608 1.04254124 0.95188952 0.84437336 0.43514427 0.20751682
 0.55179099 0.21221238 0.40205393 0.44793145]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [107]:
arr = np.random.random(10)
arr[(arr == arr.max())] = 0
print (arr)

[0.1328128  0.         0.56697697 0.93496671 0.67894637 0.81576881
 0.23180362 0.7295918  0.86187116 0.15907251]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [119]:
arr = np.zeros((5,5), [('x', float), ('y', float)])
arr['x'], arr['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print (arr)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [120]:
x = np.random.randint(-10, 10, 10)
y = np.random.randint(-10, 10, 10)
c = 1.0 / np.subtract.outer(x, y)
print (np.linalg.det(c))

0.0


/Users/soumyadeeppaul/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [122]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [125]:
arr = np.random.randint(-10, 10, 10)
print (arr)

[-1 -1 -5  0 -9  2  2 -1  3  2]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [135]:
arr = np.arange(0, 100, 1)
print (arr)
x = np.random.uniform(0, 100)
print (x)
y = arr-x
y = np.abs(y)
print (y)
index = [y==y.min()]
print (index)
print (arr[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
22.814672287336645
[22.81467229 21.81467229 20.81467229 19.81467229 18.81467229 17.81467229
 16.81467229 15.81467229 14.81467229 13.81467229 12.81467229 11.81467229
 10.81467229  9.81467229  8.81467229  7.81467229  6.81467229  5.81467229
  4.81467229  3.81467229  2.81467229  1.81467229  0.81467229  0.18532771
  1.18532771  2.18532771  3.18532771  4.18532771  5.18532771  6.18532771
  7.18532771  8.18532771  9.18532771 10.18532771 11.18532771 12.18532771
 13.18532771 14.18532771 15.18532771 16.18532771 17.18532771 18.18532771
 19.18532771 20.18532771 21.18532771 22.18532771 23.18532771 24.18532771
 25.18532771 26.18532771 27.18532771 28.18532771 29.18532771 30.18532771
 31.18532771 32.18

/Users/soumyadeeppaul/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  # Remove the CWD from sys.path while we load stuff.


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [145]:
arr = np.zeros((5, 5), [('position', [('x', float, 1), ('y', float, 1)]), 
                        ('color', [('r', float, 1), ('g', float, 1), ('b', float, 1)])])
print (arr)

[[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
  ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
  ((0., 0.), (0., 0., 0.))]
 [((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
  ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
  ((0., 0.), (0., 0., 0.))]
 [((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
  ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
  ((0., 0.), (0., 0., 0.))]
 [((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
  ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
  ((0., 0.), (0., 0., 0.))]
 [((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
  ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
  ((0., 0.), (0., 0., 0.))]]


/Users/soumyadeeppaul/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """Entry point for launching an IPython kernel.


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [152]:
arr = np.random.random((10,2))
x, y = (arr[:,0], arr[:,1])
d = (x**2 + y**2)
print (d.sum()**(1/2))

2.238186825708469


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [174]:
arr = np.random.uniform(0, 100, 20)
print (arr)
arr = arr.astype(np.int32)
print(arr)

[69.30056101 46.01517733 57.14308931 83.91246898 87.54244648 81.67315441
 19.70662751  7.02629942 19.74191728 26.01842322 62.51302012 38.95901403
 87.55555554 92.27427792  0.2152901  16.4671543  57.30988554 27.49445922
 69.61670901 77.34129801]
[69 46 57 83 87 81 19  7 19 26 62 38 87 92  0 16 57 27 69 77]


#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
arr = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(arr)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [175]:
arr = np.arange(0, 20, 1)
for index, value in np.ndenumerate(arr):
    print(index, value)

(0,) 0
(1,) 1
(2,) 2
(3,) 3
(4,) 4
(5,) 5
(6,) 6
(7,) 7
(8,) 8
(9,) 9
(10,) 10
(11,) 11
(12,) 12
(13,) 13
(14,) 14
(15,) 15
(16,) 16
(17,) 17
(18,) 18
(19,) 19


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [176]:
x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
g = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [186]:
n = 10
p = 3
arr = np.zeros((n,n))
np.put(arr, np.random.choice(range(n*n), p, replace=False),5)
print (arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 5. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [193]:
arr = np.random.randint(0, 100, 25)
arr = arr.reshape((5, 5))
m = arr.mean(axis=1)
for i in range(5):
    arr[i] = arr[i] - m[i]
print (arr)

[[ -8 -36   9  35   0]
 [-27  69 -28 -14   0]
 [ 11  15   1  -2 -27]
 [-16  44   0 -34   6]
 [-36 -23  39 -25  46]]


#### 59. How to sort an array by the nth column? (★★☆)

In [194]:
arr = np.random.randint(0,10,(3,3))
print(arr)
print(arr[arr[:,1].argsort()])

[[5 4 1]
 [1 7 1]
 [1 4 8]]
[[5 4 1]
 [1 4 8]
 [1 7 1]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [195]:
arr = np.random.randint(0, 100, (10, 10))
print (arr.all(axis=0).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [200]:
arr = np.random.randint(0, 100, (10, 10))
x = np.random.uniform(0, 100, 1)
y = arr-x
y = np.abs(y)
index = y==y.min()
print (arr[index])

[80]


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [201]:
a = np.arange(3).reshape(3,1)
b = np.arange(3).reshape(1,3)
it = np.nditer([a,b,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [202]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [203]:
arr = np.ones(10)
one = np.random.randint(0,len(Z),20)
arr = arr + np.bincount(one, minlength=len(arr))
print(arr)

[2. 6. 4. 3. 2. 2. 3. 2. 4. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [204]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [211]:
arr = np.random.randint(0, 100, (2, 4, 2, 4))
print (arr)
s = arr.sum(axis=(-1, -2))
print (s)

[[[[21 69 25 76]
   [58 64 46 75]]

  [[42 79 17 21]
   [47 93  6 65]]

  [[85 87 36 44]
   [ 5  6  9 13]]

  [[23 77  1  0]
   [14  2 31 33]]]


 [[[23 80 36 47]
   [37 22 64 44]]

  [[24  3 19 47]
   [ 6 49 98 67]]

  [[30 56 11 90]
   [21 66 41 56]]

  [[ 5 68 75 86]
   [46 19 66 83]]]]
[[434 370 285 181]
 [353 313 371 448]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [215]:
D = np.random.uniform(0,1,100)
print (D)
S = np.random.randint(0,10,100)
print (S)
D_sums = np.bincount(S, weights=D)
print (D_sums)
D_counts = np.bincount(S)
print (D_counts)
D_means = D_sums / D_counts
print(D_means)

[9.63150479e-01 9.42571510e-01 3.64821603e-01 8.55496237e-01
 7.92964822e-01 2.59357713e-01 7.07726375e-01 1.38605498e-01
 5.76557368e-01 4.56030083e-01 8.48220051e-01 1.48939894e-01
 9.68247290e-01 8.60364337e-01 6.99938587e-01 6.62345793e-01
 8.96754753e-01 3.85456042e-01 7.03109245e-01 2.21461451e-01
 6.62684697e-02 3.87789563e-01 9.42700651e-01 8.41807871e-01
 4.10220992e-01 3.47179396e-01 1.92510431e-01 6.66433140e-01
 4.99751373e-01 4.20573009e-01 5.00728244e-01 8.59146401e-01
 3.22771721e-01 3.31713041e-01 6.93924204e-01 9.00397072e-01
 6.22488188e-01 7.77932319e-01 1.97220405e-01 8.63339318e-01
 3.89843714e-01 4.26594282e-01 1.78054228e-01 6.22719226e-01
 5.79855993e-01 3.67975018e-01 2.92783463e-01 9.93490004e-01
 7.89163768e-01 5.48711202e-03 4.99145319e-01 3.03020837e-01
 2.26105889e-01 5.81745476e-01 3.32476789e-01 9.65182664e-01
 8.27106593e-01 1.15168742e-02 6.94906139e-01 7.16088091e-01
 5.03613534e-01 1.79782668e-01 2.36191731e-01 3.73242800e-04
 2.43247146e-01 3.477267

#### 69. How to get the diagonal of a dot product? (★★★)

In [219]:
arr1 = np.random.randint(0, 10, (3, 3))
arr2 = np.random.randint(0, 10, (3, 3))
arr = np.dot(arr1, arr2)
print (np.diag(arr))

[37 54 58]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [223]:
arr = np.zeros(17)
n = 3
for i in range(0, 5, 1):
    arr[4*i] = i+1
print (arr)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [225]:
arr1 = np.random.randint(0, 100, (5, 5, 3))
arr2 = np.random.randint(0, 100, (5, 5))
print(arr1 * arr2[:,:,None])

[[[1495 1219  345]
  [1650  308  968]
  [ 546 1638  168]
  [ 912  708  852]
  [ 623  672  336]]

 [[7081 9021 5238]
  [1350 1860 2310]
  [2340 1482  624]
  [1677 2494  989]
  [ 120   66  207]]

 [[ 910  448  462]
  [ 969 1020 4233]
  [2322 5848 3698]
  [ 969  561 2652]
  [2494 2320  812]]

 [[ 360  710  420]
  [1881 3036  594]
  [2352  196 1176]
  [ 305  125   20]
  [3000 2800 1160]]

 [[ 874 3634 2162]
  [4860 2214 5346]
  [4116 1932  840]
  [ 100  560  750]
  [5180 4200 5390]]]


#### 72. How to swap two rows of an array? (★★★)

In [226]:
arr = np.random.randint(0, 100, (10, 10))
print (arr)
arr[[0, 1]] = arr[[1, 0]]
print (arr)

[[21 72 92 86 91 56 12 21 38 80]
 [64 11  8 13 35  2 25 35 67 83]
 [48 94 27 42  2 13 33 94 53 33]
 [24 74 35 91 79 17 76 25 42 86]
 [94 84 38 39 36 90 38 60 91 35]
 [10 35 32 28  1 35 45 35 27 13]
 [29 82 52 67 60 57 53 61 87 64]
 [ 0 19 96 43 66 39 99 51 83 95]
 [93 57 97 14 17 94  1 64 23 91]
 [65 67 58 71 65 84 34 82 86 36]]
[[64 11  8 13 35  2 25 35 67 83]
 [21 72 92 86 91 56 12 21 38 80]
 [48 94 27 42  2 13 33 94 53 33]
 [24 74 35 91 79 17 76 25 42 86]
 [94 84 38 39 36 90 38 60 91 35]
 [10 35 32 28  1 35 45 35 27 13]
 [29 82 52 67 60 57 53 61 87 64]
 [ 0 19 96 43 66 39 99 51 83 95]
 [93 57 97 14 17 94  1 64 23 91]
 [65 67 58 71 65 84 34 82 86 36]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [227]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 5, 19) ( 5, 87) ( 9, 10) ( 9, 15) ( 9, 54) ( 9, 94) (10, 54) (15, 94)
 (17, 44) (17, 60) (19, 87) (20, 80) (20, 99) (23, 23) (23, 24) (23, 71)
 (23, 75) (24, 71) (27, 52) (27, 98) (44, 60) (48, 69) (48, 95) (52, 98)
 (66, 86) (66, 97) (69, 95) (80, 99) (86, 97)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [229]:
c = np.bincount([1,1,2,3,4,4,6])
arr = np.repeat(np.arange(len(c)), c)
print(arr)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [230]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

In [232]:
arr = np.random.randint(1, 100, 30)
arr = arr.reshape((10, 3))
print (arr)

[[96 30  7]
 [83 36 97]
 [39 75 44]
 [ 7 57 57]
 [22 64 33]
 [34 36 30]
 [50 33 23]
 [51 86 96]
 [53 12 20]
 [30  8 51]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [235]:
arr = np.random.uniform(0, 100, 50)
print (arr)
arr = np.negative(arr)
print (arr)

[ 8.36616912 63.65121228 46.82048746 41.02223454  7.65163037 14.53585023
 81.30355252 37.32049924 56.94155032 88.85443914 71.07452717 98.07895187
 70.52307858 68.2821125  44.77074801 49.74004579 88.388803   51.05697493
 77.78270162 90.8521199  63.61903294 68.05678205 49.97657312 29.36224318
 63.23640586  6.22181105 72.70041186 28.67991044  2.84819979 30.29272754
 29.63074934 70.42418813  6.61308345  8.99837022 68.14250661 83.77762741
 75.47908664 49.19629485 64.15953636 30.28184918 99.0176     77.77523034
 42.02517392 16.77017532 28.718624   17.92540964 59.28053782 14.09230194
 41.84322176 29.32186966]
[ -8.36616912 -63.65121228 -46.82048746 -41.02223454  -7.65163037
 -14.53585023 -81.30355252 -37.32049924 -56.94155032 -88.85443914
 -71.07452717 -98.07895187 -70.52307858 -68.2821125  -44.77074801
 -49.74004579 -88.388803   -51.05697493 -77.78270162 -90.8521199
 -63.61903294 -68.05678205 -49.97657312 -29.36224318 -63.23640586
  -6.22181105 -72.70041186 -28.67991044  -2.84819979 -30.2927

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [236]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 7.67057275  9.95191688  1.12611566  1.62676346  3.11689248  9.62811197
 10.67534741  6.60015172  0.92641162 12.16538448]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [237]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 1.07726199  6.74896708  3.22154346  8.46764945  1.85663253  6.43524412
   7.16483264  2.86262674  5.66192207  0.737997  ]
 [ 4.43318109 10.25160234  6.39310435 10.13608676  0.81609396  4.33882429
  11.11571201  6.09905219  5.06566576  3.00366943]
 [11.51691721 17.30339     7.82605687  8.35913596  7.76044405  2.26287204
  15.09194482  7.70275587  0.07818901  6.13875784]
 [ 9.72267284 14.6692616   5.5966908   4.3426142   9.23493192  5.9930529
   3.25461028  5.67926325  8.41883234  6.477197  ]
 [ 4.05197869  9.68365447  3.41342174  7.30868473  1.16102924  3.49340595
   8.49470033  3.12884518  3.19917773  0.20752092]
 [ 0.35010339  4.51623872  9.56984216  3.76505855  0.1604267   2.59361998
   4.00453653  9.88276944  2.53372537 12.68724475]
 [ 7.65982977 13.26337961  3.96067878  6.2198041   4.74308999  0.05554406
  10.36845574  3.76424226  0.44452693  1.63900619]
 [ 8.54452324 14.27083957  6.09183566  7.963832    5.12703873  0.03859979
  12.4839612   5.90417122  1.24363424  3.79769717]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [238]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[6 2 0 8 2 5 9 9 7 1]
 [2 8 9 6 4 1 1 7 5 0]
 [0 0 7 3 2 8 2 6 1 2]
 [3 8 9 7 6 9 7 5 2 0]
 [2 5 8 6 3 5 7 2 3 8]
 [8 1 5 3 2 4 4 0 8 3]
 [4 0 5 5 4 6 2 4 1 0]
 [7 1 9 6 3 7 3 5 4 8]
 [2 3 5 8 9 5 8 9 6 5]
 [6 1 4 0 2 5 3 8 6 4]]
[[0 0 0 0 0]
 [0 6 2 0 8]
 [0 2 8 9 6]
 [0 0 0 7 3]
 [0 3 8 9 7]]


/Users/soumyadeeppaul/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

In [240]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
new_arr = []
for i in range(len(arr)-3):
    x = []
    x.append(arr[i])
    x.append(arr[i+1])
    x.append(arr[i+2])
    x.append(arr[i+3])
    new_arr.append(x)
print (new_arr)

[[1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6], [4, 5, 6, 7], [5, 6, 7, 8], [6, 7, 8, 9], [7, 8, 9, 10], [8, 9, 10, 11], [9, 10, 11, 12], [10, 11, 12, 13], [11, 12, 13, 14]]


#### 82. Compute a matrix rank (★★★)

In [242]:
from numpy import matrix, rank
arr = matrix([[1,3,7],[2,8,3],[7,8,1]])
print (rank(arr))

2


/Users/soumyadeeppaul/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  This is separate from the ipykernel package so we can avoid doing imports until


#### 83. How to find the most frequent value in an array?

In [243]:
arr = np.random.randint(1, 100, 500)
print (np.bincount(arr).argmax())

45


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [246]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = np.lib.stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[1 1 4]
   [1 1 4]
   [4 0 0]]

  [[1 4 2]
   [1 4 0]
   [0 0 2]]

  [[4 2 2]
   [4 0 0]
   [0 2 0]]

  [[2 2 0]
   [0 0 3]
   [2 0 3]]

  [[2 0 3]
   [0 3 2]
   [0 3 0]]

  [[0 3 0]
   [3 2 0]
   [3 0 1]]

  [[3 0 4]
   [2 0 0]
   [0 1 0]]

  [[0 4 4]
   [0 0 4]
   [1 0 2]]]


 [[[1 1 4]
   [4 0 0]
   [4 3 4]]

  [[1 4 0]
   [0 0 2]
   [3 4 1]]

  [[4 0 0]
   [0 2 0]
   [4 1 3]]

  [[0 0 3]
   [2 0 3]
   [1 3 2]]

  [[0 3 2]
   [0 3 0]
   [3 2 1]]

  [[3 2 0]
   [3 0 1]
   [2 1 4]]

  [[2 0 0]
   [0 1 0]
   [1 4 4]]

  [[0 0 4]
   [1 0 2]
   [4 4 4]]]


 [[[4 0 0]
   [4 3 4]
   [1 1 3]]

  [[0 0 2]
   [3 4 1]
   [1 3 4]]

  [[0 2 0]
   [4 1 3]
   [3 4 0]]

  [[2 0 3]
   [1 3 2]
   [4 0 2]]

  [[0 3 0]
   [3 2 1]
   [0 2 4]]

  [[3 0 1]
   [2 1 4]
   [2 4 4]]

  [[0 1 0]
   [1 4 4]
   [4 4 3]]

  [[1 0 2]
   [4 4 4]
   [4 3 1]]]


 [[[4 3 4]
   [1 1 3]
   [2 2 3]]

  [[3 4 1]
   [1 3 4]
   [2 3 3]]

  [[4 1 3]
   [3 4 0]
   [3 3 1]]

  [[1 3 2]
   [4 0 2]
   [3 1 3]]

  [[3 2 1]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

In [244]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 8  3  2  8  6]
 [ 3  0 12 15 13]
 [ 2 12  5 42 10]
 [ 8 15 42  1  6]
 [ 6 13 10  6  6]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [247]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [248]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0), np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [249]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [250]:
arr = np.random.randint(1, 100, 50)
n = 5
print (arr[np.argsort(arr)[-n:]])

[91 92 95 96 96]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [251]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [252]:
Z = np.array([("Hello", 2.5, 3),("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,names='col1, col2, col3',formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [257]:
x = np.random.randint(1, 100, 1)

print (np.power(x,3))
print (x*x*x)
print (np.einsum('i,i,i->i',x,x,x))

[64]
[64]
[64]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [258]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 3 4 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [259]:
Z = np.random.randint(0,5,(10,3))
print(Z)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[1 4 0]
 [4 2 0]
 [2 3 4]
 [3 3 2]
 [2 4 2]
 [1 4 1]
 [3 4 1]
 [4 2 2]
 [0 3 3]
 [4 0 3]]
[[1 4 0]
 [4 2 0]
 [2 3 4]
 [3 3 2]
 [2 4 2]
 [1 4 1]
 [3 4 1]
 [4 2 2]
 [0 3 3]
 [4 0 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [260]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [261]:
arr = np.random.randint(0,2,(6,3))
arr = np.unique(arr, axis=0)
print(arr)

[[0 1 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [262]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)
np.einsum('i,i->i', A, B)
np.einsum('i,i', A, B)
np.einsum('i,j->ij', A, B)

array([[0.03573262, 0.09259094, 0.35611239, 0.1326334 , 0.12927326,
        0.04453591, 0.25583484, 0.2171001 , 0.36746121, 0.02756051],
       [0.01043676, 0.0270439 , 0.10401306, 0.03873947, 0.03775804,
        0.01300802, 0.07472406, 0.06341045, 0.10732781, 0.00804985],
       [0.00170104, 0.00440777, 0.01695266, 0.00631399, 0.00615403,
        0.00212012, 0.01217896, 0.01033501, 0.01749291, 0.00131201],
       [0.04852468, 0.12573792, 0.48359836, 0.18011532, 0.17555226,
        0.06047949, 0.34742209, 0.29482056, 0.49900999, 0.03742699],
       [0.0675136 , 0.17494233, 0.6728426 , 0.25059898, 0.24425029,
        0.08414664, 0.48337712, 0.41019128, 0.69428519, 0.05207312],
       [0.01413336, 0.03662259, 0.14085351, 0.05246063, 0.05113159,
        0.01761534, 0.10119062, 0.08586983, 0.14534232, 0.01090104],
       [0.06085   , 0.1576755 , 0.60643295, 0.22586483, 0.22014275,
        0.07584135, 0.43566773, 0.36970535, 0.62575915, 0.04693349],
       [0.01515307, 0.03926489, 0.1510159

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [264]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)
r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x)
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [265]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [266]:
X = np.random.randn(100)
N = 1000
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.3792783 -0.0207588]
